export const CartDropdownTypes ={
    TOGGLE_CART_DROPDOWN_HIDDEN: 'TOGGLE_CART_DROPDOWN_HIDDEN',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    CLEAR_ITEM_FROM_CART:'CLEAR_ITEM_FROM_CARD'
}